#!/bin/bash

if [ -z $1 ] ; then
  echo "Usage: $0 <file>"
  exit 1
fi
if [ "$1" == "-h" ] ; then
  echo "Usage: $0 <file>"
  exit 1
fi

cat <<END
<ac:structured-macro ac:name="warning" ac:schema-version="1" ac:macro-id="02b4cd02-522c-414e-b626-c48ce4bc143f"><ac:rich-text-body><p>Do not edit this file! It is autogenerated and will be overwritten!</p></ac:rich-text-body></ac:structured-macro><ac:structured-macro ac:macro-id="616a0c72-8244-450a-ad14-37800fd227be" ac:name="code" ac:schema-version="1"><ac:parameter ac:name="linenumbers">true</ac:parameter><ac:plain-text-body><![CDATA[
END
cat $1
cat <<END
]]></ac:plain-text-body></ac:structured-macro>
END
exit 0
